name: Pull Request processing
# This workflow is triggered on pushes to the repository.
on: [pull_request]

jobs:
  build:
    name: Run dbt, export images and deploy docs site
    runs-on: ubuntu-latest
    container: python:3.8
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      POSTGRES_HOSTNAME: postgres
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB_NAME: postgres
      POSTGRES_SCHEMA_NAME: artwork
    
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v1

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: 'Run dbt'
        run: |
          export POSTGRES_HOSTNAME=${{ env.POSTGRES_HOSTNAME }}
          export POSTGRES_USERNAME=${{ env.POSTGRES_USERNAME }}
          export POSTGRES_PASSWORD=${{ env.POSTGRES_PASSWORD }}
          chmod +x ./ci/run_dbt.sh
          ./ci/run_dbt.sh
          mkdir target/images

      - name: 'Render images and save docs'
        run: |
          export POSTGRES_HOSTNAME=${{ env.POSTGRES_HOSTNAME }}
          export POSTGRES_USERNAME=${{ env.POSTGRES_USERNAME }}
          export POSTGRES_PASSWORD=${{ env.POSTGRES_PASSWORD }}
          pip install -r requirements.txt
          # Queries all the models in the database, uses matplotlib to render pngs from them
          python ./ci/render_images_from_db.py
          # Modifies the docs manifest.json to include images of each model
          python ./ci/add_image_links_to_manifest.py

      - name: Save PR number
        run: |
          mkdir -p ./pr
          echo ${{ github.event.number }} > ./pr/NR

      - uses: actions/upload-artifact@v2
        with:
          name: pr
          path: pr/

      - uses: actions/upload-artifact@v2
        with:
          name: docs
          path: target/



